Добавила определения и примеры числовых множеств
FpXL/math pull request #10
Opened 2024-11-09 20:19 UTC by dinakazakevich

- Добавила определения и примеры числовых множеств, сделала отдельные файлы для них
- Добавила замечание про то, что в определенных дисциплинах и соглашениях 0 может входить в натуральные числа
- Добавила иррациональные как отдельное множество 
- Исправила ошибку в определении Q (~~целых~~ > рациональных)

2024-11-09 21:23 UTC, FpXL requested changes
Одна обязательная правка, остальное на усмотрение.

2024-11-09 21:23 UTC, FpXL commented on Множество натуральных чисел.md
> +Обозначается $\mathbb{N} = \{1; 2; 3; ...; n; ...\}$  это числа, которые используются для счёта и включают положительные целые числа.
:nit хорошо бы договориться как писать элементы множества: через , или ;. В этом файле сразу два варианта

2024-11-09 21:23 UTC, FpXL commented on Множество натуральных чисел.md
> +2. **Альтернативное определение (начиная с 0)**: В ряде стран, особенно в США и в некоторых направлениях математики и компьютерных наук, принято считать, что натуральные числа **включают 0**. В этом
:nit Не считайте меня душнилой, но я за букву "ё" :)

2024-11-09 21:23 UTC, FpXL commented on Множество рациональных чисел.md
> +Это числа, которые можно выразить в виде дроби pq\frac{p}{q}qp​, где ppp и qqq — целые числа, и q≠0q \neq 0q=0.
не отображаются формулы и кривая кодировка

2024-11-09 21:23 UTC, FpXL commented on Числовые множества.md
> +* [[Множество иррациональных чисел]] $\sqrt{2}$, $\pi$, $e$
nit: $\mathbb{I} = \mathbb{R} \setminus \mathbb{Q}$ — [[Множество иррациональных чисел]]

2024-11-12 19:10 UTC, dinakazakevich commented on Числовые множества.md
> +* [[Множество иррациональных чисел]] $\sqrt{2}$, $\pi$, $e$
Исправила. Спасибо!

2024-11-12 19:10 UTC, dinakazakevich commented on Множество рациональных чисел.md
> +Это числа, которые можно выразить в виде дроби pq\frac{p}{q}qp​, где ppp и qqq — целые числа, и q≠0q \neq 0q=0.
Исправила. Спасибо!

2024-11-12 19:10 UTC, dinakazakevich commented on Множество натуральных чисел.md
> +2. **Альтернативное определение (начиная с 0)**: В ряде стран, особенно в США и в некоторых направлениях математики и компьютерных наук, принято считать, что натуральные числа **включают 0**. В этом
Вовсе нет! Исправила.

2024-11-12 19:10 UTC, dinakazakevich commented on Множество натуральных чисел.md
> +Обозначается $\mathbb{N} = \{1; 2; 3; ...; n; ...\}$  это числа, которые используются для счёта и включают положительные целые числа.
Исправила!

2024-11-12 19:34 UTC, FpXL approved these changes

2024-11-15 19:55 UTC, merged